-- CREATING THE DATABASE
create database sales; 


--- USE DATABASE
use sales;

-- IMPORT THE CSV FILE

-- INSPECTING THE DATA
SELECT * FROM SALE;

-- CHECKING UNIQUE VALUES
SELECT DISTINCT(STATUS) FROM SALE;
SELECT DISTINCT(YEAR_ID) FROM SALE;
SELECT DISTINCT(PRODUCTLINE) FROM SALE;
SELECT DISTINCT(COUNTRY) FROM SALE;
SELECT DISTINCT(DEALSIZE) FROM SALE;
SELECT DISTINCT(TERRITORY) FROM SALE;
SELECT DISTINCT(CUSTOMERNAME) FROM SALE;



-- ANALYSIS
-- 1. ACROSS ALL THEIR PRODUCTLINE,WHICH ONE IS THE BEST SELLING?

-- STARTING WITH GROUPING THE SALES WITH PRODUCTLINE
SELECT PRODUCTLINE,SUM(SALES) FROM SALE GROUP BY PRODUCTLINE ORDER BY SUM(SALES) DESC; 

-- THIS SHOW THAT CLASSIC CARS IS THE BEST SELLING PRODUCTLINE


-- 2. WHAT IS THE BEST YEARS FOR SALES?
-- GROUPING THE SALES WITH THE YEAR

SELECT YEAR_ID,SUM(SALES) FROM SALE GROUP BY YEAR_ID ORDER BY SUM(SALES) DESC;

-- THIS SHOW THAT THE HIGHEST SALE WAS MADE IN 2004 AND THE LEAST SALE WAS MADE THE FOLLOWING YEAR 2005

-- FIND OUT THE REASON WHY THE SALE WAS LESS IN 2005

SELECT DISTINCT (MONTH_ID) FROM SALE WHERE YEAR_ID=2005 ORDER BY MONTH_ID;
-- IT IS SEEN THAT BUSINESS OPERATION ONLY WENT FOR 5 MONTHS I.E JANUARY TO MAY

SELECT DISTINCT (MONTH_ID) FROM SALE WHERE YEAR_ID=2004 ORDER BY MONTH_ID;
-- BUSINEES OPEARTION WAS ONGOING THROUGH OUT THE 12 MONTHS IN 2004

SELECT DISTINCT (MONTH_ID) FROM SALE WHERE YEAR_ID=2003 ORDER BY MONTH_ID;
-- ALSO IN BUSINEES OPEARTION WAS ONGOING THROUGH OUT THE 12 MONTHS IN 2003


-- SO THE REAON FOR LESS SALES IN 2005 IS CLEAR BECAUSE THEY OPERATED  FOR ONLY 5 MONTHS 


-- 3.WHAT WAS THE BEST MONTH FOR SALES IN A SPECIFIC YEAR ? HOW MUCH EARNED WAS THAT MONTH ?


SELECT MONTH_ID,SUM(SALES) FROM SALE WHERE YEAR_ID=2003 -- CHANGE YEAR TO SEE THE REST 
GROUP BY MONTH_ID ORDER BY SUM(SALES) DESC;

-- IT SHOW THAT NOVEMBER IS THE BEST MONTH FOR SALE IN 2003

-- 4. NOW FIND OUT THE PRODUCTLINE THAT SOLD MOST IN NOVEMBER OF EACH YEAR

SELECT MONTH_ID,PRODUCTLINE,SUM(SALES),COUNT(ORDERNUMBER) FROM SALE WHERE YEAR_ID=2003 AND MONTH_ID=11 GROUP BY MONTH_ID,PRODUCTLINE ORDER BY 3 DESC;

-- CLASSIC CARS WAS THE MOST SELLING PRODUCT IN NOVEMBER 2003

-- 5. WHO COUNTRY SOLD THE MOST PRODUCT?
SELECT COUNTRY,SUM(SALES) FROM SALE GROUP BY COUNTRY ORDER BY 2 DESC;

-- THE DATA REVEALED THAT USA SOLD THE MOST PRODUCTS OUT OF THE OTHER 19 COUNTRIES


